TYPO3:
  Neos:
    nodeTypes:
      groups:
        search:
          position: 'end'
          label: 'ObisConcept.NeosSearch:Main:nodeTypes.groups.search'
          collapsed: false

    typoScript:
      autoInclude:
        'ObisConcept.NeosSearch': TRUE

    userInterface:
      translation:
        autoInclude:
          'ObisConcept.NeosSearch': ['Main', 'NodeTypes/*']

ObisConcept:
  NeosSearch:
    templateRootPath: 'resource://ObisConcept.NeosSearch/Private/Templates/'